{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module Parser.PrintHopper where

-- pretty-printer generated by the BNF converter

import Parser.AbsHopper
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)



instance Print IdVar where
  prt _ (IdVar i) = doc (showString ( i))


instance Print IdCon where
  prt _ (IdCon i) = doc (showString ( i))


instance Print IdOpr where
  prt _ (IdOpr i) = doc (showString ( i))



instance Print Module where
  prt i e = case e of
   MMod idcon exports defs -> prPrec i 0 (concatD [doc (showString "module") , prt 0 idcon , prt 0 exports , doc (showString "where") , doc (showString ";") , prt 0 defs])


instance Print Exports where
  prt i e = case e of
   NEmpty  -> prPrec i 0 (concatD [])
   NExps exports -> prPrec i 0 (concatD [doc (showString "(") , prt 0 exports , doc (showString ")")])


instance Print Export where
  prt i e = case e of
   NExp idvar -> prPrec i 0 (concatD [prt 0 idvar])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Def where
  prt i e = case e of
   DFun func -> prPrec i 0 (concatD [prt 0 func])
   DSig sign -> prPrec i 0 (concatD [prt 0 sign])
   DAdt adt -> prPrec i 0 (concatD [prt 0 adt])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Func where
  prt i e = case e of
   FFun idvar args expr -> prPrec i 0 (concatD [prt 0 idvar , prt 0 args , doc (showString "=") , doc (showString "{") , prt 0 expr , doc (showString "}")])


instance Print Arg where
  prt i e = case e of
   AId id -> prPrec i 0 (concatD [prt 0 id])
   APrim prim -> prPrec i 0 (concatD [prt 0 prim])
   AWild  -> prPrec i 0 (concatD [doc (showString "_")])
   ATuple argtuples -> prPrec i 0 (concatD [doc (showString "(") , prt 0 argtuples , doc (showString ")")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print ArgTuple where
  prt i e = case e of
   ArCon idcon arg args -> prPrec i 0 (concatD [prt 0 idcon , prt 0 arg , prt 0 args])
   ArArg arg -> prPrec i 0 (concatD [prt 0 arg])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Expr where
  prt i e = case e of
   EId id -> prPrec i 2 (concatD [prt 0 id])
   EPrim prim -> prPrec i 2 (concatD [prt 0 prim])
   EOpr idopr -> prPrec i 2 (concatD [doc (showString "(") , prt 0 idopr , doc (showString ")")])
   EInfix expr0 idopr expr -> prPrec i 1 (concatD [prt 1 expr0 , prt 0 idopr , prt 2 expr])
   EApp expr0 expr -> prPrec i 1 (concatD [prt 1 expr0 , prt 2 expr])
   ECase expr clas -> prPrec i 1 (concatD [doc (showString "case") , prt 1 expr , doc (showString "of") , doc (showString "{") , prt 0 clas , doc (showString "}")])
   EIf expr0 expr1 expr -> prPrec i 1 (concatD [doc (showString "if") , prt 1 expr0 , doc (showString "then") , prt 2 expr1 , doc (showString "else") , prt 2 expr])
   ELambda pats expr -> prPrec i 0 (concatD [doc (showString "\\") , prt 0 pats , doc (showString "->") , prt 0 expr])


instance Print Cla where
  prt i e = case e of
   CClause pat expr -> prPrec i 0 (concatD [prt 0 pat , doc (showString "->") , prt 0 expr])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Pat where
  prt i e = case e of
   PId id -> prPrec i 0 (concatD [prt 0 id])
   PPrim prim -> prPrec i 0 (concatD [prt 0 prim])
   PWild  -> prPrec i 0 (concatD [doc (showString "_")])
   PTuple pattuples -> prPrec i 0 (concatD [doc (showString "(") , prt 0 pattuples , doc (showString ")")])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print PatTuple where
  prt i e = case e of
   PaCon idcon pat pats -> prPrec i 0 (concatD [prt 0 idcon , prt 0 pat , prt 0 pats])
   PaPat pat -> prPrec i 0 (concatD [prt 0 pat])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Sign where
  prt i e = case e of
   SSig idvar types -> prPrec i 0 (concatD [prt 0 idvar , doc (showString "::") , doc (showString "{") , prt 0 types , doc (showString "}")])


instance Print Type where
  prt i e = case e of
   TName idcon ids -> prPrec i 0 (concatD [prt 0 idcon , prt 0 ids])
   TVar idvar ids -> prPrec i 0 (concatD [prt 0 idvar , prt 0 ids])
   TTuple typetuples -> prPrec i 0 (concatD [doc (showString "(") , prt 0 typetuples , doc (showString ")")])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString "->") , prt 0 xs])

instance Print TypeTuple where
  prt i e = case e of
   TyTuple types -> prPrec i 0 (concatD [prt 0 types])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Adt where
  prt i e = case e of
   AAdt idcon adtvars conss -> prPrec i 0 (concatD [doc (showString "data") , prt 0 idcon , prt 0 adtvars , doc (showString "=") , doc (showString "{") , prt 0 conss , doc (showString "}")])


instance Print AdtVar where
  prt i e = case e of
   AdVar idvar -> prPrec i 0 (concatD [prt 0 idvar])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Cons where
  prt i e = case e of
   CCon idcon ids -> prPrec i 0 (concatD [prt 0 idcon , prt 0 ids])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString "|") , prt 0 xs])

instance Print Id where
  prt i e = case e of
   ICon idcon -> prPrec i 0 (concatD [prt 0 idcon])
   IVar idvar -> prPrec i 0 (concatD [prt 0 idvar])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Prim where
  prt i e = case e of
   IInteger n -> prPrec i 0 (concatD [prt 0 n])
   IDouble d -> prPrec i 0 (concatD [prt 0 d])
   IString str -> prPrec i 0 (concatD [prt 0 str])
   IChar c -> prPrec i 0 (concatD [prt 0 c])



