module Parser.SkelHopper where

-- Haskell module generated by the BNF converter

import Parser.AbsHopper
import Utils.ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdVar :: IdVar -> Result
transIdVar x = case x of
  IdVar str  -> failure x


transIdCon :: IdCon -> Result
transIdCon x = case x of
  IdCon str  -> failure x


transIdOpr :: IdOpr -> Result
transIdOpr x = case x of
  IdOpr str  -> failure x


transModule :: Module -> Result
transModule x = case x of
  MModule idcon exports defs  -> failure x


transExport :: Export -> Result
transExport x = case x of
  MExport idvar  -> failure x


transDef :: Def -> Result
transDef x = case x of
  DSig idvar types  -> failure x
  DFun idvar args exp  -> failure x
  DDat idcon conss  -> failure x


transCons :: Cons -> Result
transCons x = case x of
  FCon idcon pars  -> failure x


transPar :: Par -> Result
transPar x = case x of
  GCon idcon  -> failure x


transArg :: Arg -> Result
transArg x = case x of
  ACon idcon  -> failure x
  AVar idvar  -> failure x
  AWild  -> failure x
  AString str  -> failure x
  AChar c  -> failure x
  AInteger n  -> failure x
  ADouble d  -> failure x
  ATuple bargs  -> failure x


transBarg :: Barg -> Result
transBarg x = case x of
  BCon idcon args  -> failure x
  BArg arg  -> failure x


transType :: Type -> Result
transType x = case x of
  TName idcon  -> failure x
  TVar idvar  -> failure x
  TFun type' types  -> failure x


transExp :: Exp -> Result
transExp x = case x of
  EVar idvar  -> failure x
  ECon idcon  -> failure x
  EOpr idopr  -> failure x
  EString str  -> failure x
  EChar c  -> failure x
  EInteger n  -> failure x
  EDouble d  -> failure x
  EInfix exp1 idopr2 exp3  -> failure x
  EApp exp1 exp2  -> failure x
  ECase exp clas  -> failure x
  EIf exp1 exp2 exp3  -> failure x
  ELambda pats exp  -> failure x


transCla :: Cla -> Result
transCla x = case x of
  CClause pat exp  -> failure x


transPat :: Pat -> Result
transPat x = case x of
  PCon idcon  -> failure x
  PVar idvar  -> failure x
  PWild  -> failure x
  PString str  -> failure x
  PChar c  -> failure x
  PInteger n  -> failure x
  PDouble d  -> failure x



